query Me {
  me {
    id
    email
    name
    firstName
    lastName
    middleName
    description
    photoUrl
    birthDate
    createdAt
  }
}

mutation Register($email: String!, $password: String!, $name: String) {
  register(email: $email, password: $password, name: $name) {
    user {
      id
      email
      name
      firstName
      lastName
      middleName
      description
      photoUrl
      birthDate
      createdAt
    }
  }
}

mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    user {
      id
      email
      name
      firstName
      lastName
      middleName
      description
      photoUrl
      birthDate
      createdAt
    }
  }
}

mutation Refresh {
  refresh {
    user {
      id
      email
      name
      firstName
      lastName
      middleName
      description
      photoUrl
      birthDate
      createdAt
    }
  }
}

mutation Logout {
  logout
}
