type User {
  id: ID!
  email: String!
  name: String
  firstName: String
  lastName: String
  middleName: String
  description: String
  photoUrl: String
  birthDate: String
  createdAt: String!
}

type AuthPayload {
  user: User!
}

input UpdateProfileInput {
  firstName: String
  lastName: String
  middleName: String
  description: String
  birthDate: String
}

input UploadProfilePhotoInput {
  fileName: String!
  base64: String!
}

type Query {
  me: User
}

type Mutation {
  register(email: String!, password: String!, name: String): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  refresh: AuthPayload!
  logout: Boolean!
  updateProfile(input: UpdateProfileInput!): AuthPayload!
  uploadProfilePhoto(input: UploadProfilePhotoInput!): AuthPayload!
  deleteProfilePhoto: AuthPayload!
}
