#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

echo "Typecheck: frontend"
(cd frontend && yarn tsc --noEmit)

echo "Typecheck: backend"
(cd backend && npx tsc -p tsconfig.json --noEmit)

echo "Lint: frontend"
(cd frontend && yarn lint --fix)

echo "Lint: backend"
(cd backend && npm run lint -- --fix)

echo "Format: prettier"
npx prettier --write .
git add -A
